### ISSUE TITLE
Kebab-case notation

### ISSUE THREAD

**Issue by martoio** [samueldowd/colmar-academy#2]
Best practice tip: Use ``kebab-case-notation`` for your ID/class names in HTML and CSS. It makes things easier to read and it's an established industry practice.

https://github.com/samueldowd/colmar-academy/blob/2c9bfe705f1bc1fe7f802cadf1eea82438b888f2/index.html#L43

**Comment by samueldowd** [comment]
I probably won't change this for this project, but it's good to keep in mind for the future. Thanks!
