### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by martoio** [samueldowd/colmar-academy#3]
Make sure you add the ``alt`` attribute to your images to maintain accessibility for all audiences of the page (particularly visually-impaired users). Remember to add it even in these simple projects and it will become a habit. (Hint: as long as you have the ``alt`` attribute with something semi-meaningful, we'll be happy with it).
For more info: https://www.codecademy.com/articles/accessibility

https://github.com/samueldowd/colmar-academy/blob/2c9bfe705f1bc1fe7f802cadf1eea82438b888f2/index.html#L74

**Comment by samueldowd** [comment]
Resolved in https://github.com/samueldowd/colmar-academy/commit/aa65343b2b9abd56004cbf891a3dafabd7fcc371
